language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install:
  - bash .travis/install_dependencies.sh

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DCMAKE_INSTALL_PREFIX=../install ..
  - make
  - make test
